url: "http://trulyflorida.net" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Truly Florida" # the name of your site, e.g. ACME Corp.
email: dan@dmcarroll.net
description: ""

sass:
    style: compressed

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  tags:
    output: true
    permalink: /tags/:path/    
  parks:
    output: true
    permalink: /parks/:path/
  beaches:
    output: true
    permalink: /beaches/:path/
  attractions:
    output: true
    permalink: /attractions/:path/
  events:
    output: true
    permalink: /events/:path/
  food-n-drink:
    output: true
    permalink: /food-n-drink/:path/
  shops:
    output: true
    permalink: /shops/:path/
  markets:
    output: true
    permalink: /markets/:path/
  shopping:
    output: true
    permalink: /shopping/:path/
